"""
AsterSurge Executor

Version: 0.2.0
"""


class Executor:
    """
    Executes plans generated by the planner.
    """

    def __init__(self, registry=None):
        self.registry = registry

    def execute(self, plan):
        """
        Execute a plan.

        Returns:
            list
        """

        results = []

        for step in plan:

            tool = step.get("tool")
            action = step.get("action")

            if (
                self.registry
                and tool
                and self.registry.get("tools", tool)
            ):
                handler = self.registry.get(
                    "tools",
                    tool,
                )

                output = handler(action)

            else:
                output = {
                    "status": "skipped",
                    "reason": "No handler registered.",
                }

            results.append(
                {
                    "step": step,
                    "output": output,
                }
            )

        return results

    def execute_step(self, step):
        """
        Execute a single step.
        """
        return self.execute([step])[0]
